### ISSUE TITLE
hmyv2_getBlockSignersKeys parameters

### ISSUE THREAD

**Issue by difengJ** [harmony-one/pyhmy#17]
![image](https://user-images.githubusercontent.com/19460327/112795513-35179280-909b-11eb-806e-0cbad7d58133.png)
the parameters are not aligned with request example.
[api url](https://api.hmny.io/#9f9c8298-1a4e-4901-beac-f34b59ed02f1)
I think the parameter is block_num only.

can anyone help to update it?

**Comment by MaxMustermann2** [comment]
This appears to have been updated.

![Screenshot-20220825010909-349x221](https://user-images.githubusercontent.com/82761650/186508144-d3164e51-1f75-4880-84b6-a020f487a06b.png)
