### ISSUE TITLE
Solved: Transaction related code from examples section doesnt work

### ISSUE THREAD

**Issue by magniff** [harmony-one/pyhmy#23]
# Lib version:
`668d7ef756e4fefe4621f435bb9a3e37cbeb82d9`
# The problem:
I am trying to issue a simple fund-transferring transaction. The code, according to the project's `README` should look like this:
```python
import pyhmy.transaction as t
import pyhmy.signing as s


bobPub = "one1mfzkvvtsjzagnkxc3ad4lndnfk92hpla70nf24"
# Bob is a testing acc with only testnet ONEs
bobPriv = "c07bfdf4819946009c06bfee12f9ef2d37c1a216600961460121f1c085d16316"
magniffPub = "one10glu5d2sxyn5gcg0e6yd7v7ty4vptjs3pr0spc"

testNetAddress = "https://api.s0.b.hmny.io"

tx = {
 'chainId': 2,
 'from': bobPub,
 'gas': 6721900,
 'gasPrice': 1000000000,
 'nonce': 10101,
 'shardID': 0,
 'to': magniffPub,
 'toShardID': 0,
 'value': 10 ** 15,
}


print(t.send_raw_transaction(
    s.sign_transaction(tx, bobPriv).rawTransaction.hex(), testNetAddress
))
```
It actually gives me back the transaction id, yet it could not be found on explorer, nor funds are transferred.

**Comment by Severino** [comment]
I had the problem, that my version from pip was outdated as described in #21

When I cloned the repo and build the library manually (also described in #21), it worked with your code flawlessly.
0xcc8eacff538f268b10789443b543a00617864b5b4095fbbde6e9d3626b617c4f

Only thing I noticed, that you wrote at bobPriv: "0x" as privatekey. The privatekey has no 0x prefix. maybe that's also an issue. Are you using the correct private key?

**Comment by magniff** [comment]
> I had the problem, that my version from pip was outdated as described in #21
> 
> When I cloned the repo and build the library manually (also described in #21), it worked with your code flawlessly. 0xcc8eacff538f268b10789443b543a00617864b5b4095fbbde6e9d3626b617c4f
> 
> Only thing I noticed, that you wrote at bobPriv: "0x" as privatekey. The privatekey has no 0x prefix. maybe that's also an issue. Are you using the correct private key?

Ok, since Bob is a testing account, I've edited in a real private key, could you please try again? Problem reproduces on the `668d7ef756e4fefe4621f435bb9a3e37cbeb82d9` revision - it is the most recent `master`.

**Comment by johnashu** [comment]
Maybe it is due to the Nonce being too high?

This worked for me AFTER getting the Nonce value.

before it did not show the tx hash in explorer.

``` python
import pyhmy.transaction as t
import pyhmy.signing as s
import pyhmy.account as a


bobPub = "one1mfzkvvtsjzagnkxc3ad4lndnfk92hpla70nf24"
# Bob is a testing acc with only testnet ONEs
bobPriv = "c07bfdf4819946009c06bfee12f9ef2d37c1a216600961460121f1c085d16316"
magniffPub = "one10glu5d2sxyn5gcg0e6yd7v7ty4vptjs3pr0spc"

testNetAddress = "https://api.s0.b.hmny.io"
nonce = a.get_account_nonce(bobPub, block_num='latest', endpoint=testNetAddress)

tx = {
 'chainId': 2,
 'from': bobPub,
 'gas': 25000,
 'gasPrice': 1000000000,
 'nonce': nonce,
 'shardID': 0,
 'to': magniffPub,
 'toShardID': 0,
 'value': 10 ** 15,
}


tx_hash = t.send_raw_transaction(
    s.sign_transaction(tx, bobPriv).rawTransaction.hex(), testNetAddress
)
print(tx_hash)

```

**Comment by magniff** [comment]
> Maybe it is due to the Nonce being too high?
> 
> This worked for me AFTER getting the Nonce value.
> 
> before it did not show the tx hash in explorer.
> 
> ```python
> import pyhmy.transaction as t
> import pyhmy.signing as s
> import pyhmy.account as a
> 
> 
> bobPub = "one1mfzkvvtsjzagnkxc3ad4lndnfk92hpla70nf24"
> # Bob is a testing acc with only testnet ONEs
> bobPriv = "c07bfdf4819946009c06bfee12f9ef2d37c1a216600961460121f1c085d16316"
> magniffPub = "one10glu5d2sxyn5gcg0e6yd7v7ty4vptjs3pr0spc"
> 
> testNetAddress = "https://api.s0.b.hmny.io"
> nonce = a.get_account_nonce(bobPub, block_num='latest', endpoint=testNetAddress)
> 
> tx = {
>  'chainId': 2,
>  'from': bobPub,
>  'gas': 25000,
>  'gasPrice': 1000000000,
>  'nonce': nonce,
>  'shardID': 0,
>  'to': magniffPub,
>  'toShardID': 0,
>  'value': 10 ** 15,
> }
> 
> 
> tx_hash = t.send_raw_transaction(
>     s.sign_transaction(tx, bobPriv).rawTransaction.hex(), testNetAddress
> )
> print(tx_hash)
> ```

It must be it, thanks.
