### ISSUE TITLE
ModuleNotFoundError: No module named 'pyhmy.bech32' after installing in Anaconda Environment

### ISSUE THREAD

**Issue by lukaszlaszczuk** [harmony-one/pyhmy#26]
Getting `ModuleNotFoundError: No module named 'pyhmy.bech32'` error after installing with `pip install pyhmy` in Anaconda Environment on Ubuntu.

**Comment by alibama** [comment]
yeah - ditto = pip install'ed bech32 to see if that would solve it = no such luck

**Comment by johnashu** [comment]
You need to add an `__init__.py` to the bech32 folder and install manually using `setup.py`..

See Pull request here: https://github.com/harmony-one/pyhmy/pull/24

**Comment by yurenji** [comment]
+1

**Comment by lamk0006** [comment]
Have this issue too and it has been there for months now
