### ISSUE TITLE
Update eth-account requirement to >=0.5.6

### ISSUE THREAD

**Issue by rslider00** [harmony-one/pyhmy#30]
There currently exists a pip dependency conflict with Web3; namely, Web3 requires eth-account<0.6.0,>=0.5.6, but pyhmy's setup.cfg explicitly requires 0.5.4.

Unless this older version is used for a specific reason, pyhmy should be updated to use a newer version of eth-account, such as 0.5.7.

**Comment by jazcto86** [comment]
bump!
